### PR TITLE
Implement parallel file IO for streamerless download

### PR DESCRIPTION
**Pull request by p2004a**
The main goal is to improve download performance on Windows as there is a lot of overhead when creating
many small files caused by antivirus software.

It improves download of `byar:test` on my internet connection:
- Linux: ~18.5s -> ~13.5s
- Windows: ~50s -> ~22s

~I still have some profiling and tuning to do to see what is the bottleneck on Windows and if we can make it as performant as on Linux, but I would like to submit this bulk of code already for the review.~

Tested some simple ideas, but not much gained. Overall even when I drop File IO altogether, Windows still takes ~18s, so looks like curl itself is less optimized for that platform.

---
#### Implementation

100% of file operations and hashing of content to verify that file content is correct is moved to a dedicated thread pool. Each file belongs to a single random thread. Tasks on the thread pool are only accessing the file object, hash object, and io failure flag. File operation errors are communicated asynchronously back to the main thread that will then cancel the download.

### CODE REVIEW

**Comment by lhog** [comment]
The main engine uses `moodycamel` to put together ThreadPool. Is there any chance to harmonize with the engine implementation instead? Otherwise summoning @marcushutchings for his expert view on MT.

**Comment by p2004a** [comment]
I see engine is using move MPMC queue, I'm using simple SPSC variant, with queue per thread (it's good enough here) The thread pool here is very, very simple. The one in engine is more complex with a different feature set, but looking at the code, I could probably make it work here.

The thing is I don't think it's easily feasible to make that thread pool available here. Probably possible with a bunch of ifdefs and cmake magic but I'm not sure if it's worth it?

**Comment by lhog** [comment]
It's ok, it was just a question. If bringing engine constructs is more troublesome than valuable then by all means don't hesitate to continue with your own implementation

In general I'm sure you tested this one quite extensively so go ahead and merge it. There's currently no one around knowing pr-d better than you do. Own it :)

**Comment by p2004a** [comment]
> It's ok, it was just a question

Of course, just tried to answer it well :smile:.

Overall I like to have somebody to at least skim what I'm doing to avoid some stupid mistakes ;)

**Pull request merged**
